// <auto-generated />
namespace renta_autos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Cambios1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cambios1));
        
        string IMigrationMetadata.Id
        {
            get { return "202102241944196_Cambios1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
